### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by mattbretl** [graphile/postgis#10]
Any plans for the test suite? The one I use for my plugins isn't the greatest, but I could bring it in as a starting point.

**Comment by benjie** [comment]
I like the worker's one: https://github.com/graphile/worker; but whatever works. Here's a few recommendations:

- use jest
- use snapshots where appropriate
- create a new uniquely named schema (e.g. `graphile_postgis`) and a schema file that starts `create extension if not exists postgis using schema public; drop schema if exists graphile_postgis cascade; create schema graphile_postgis; set search_path to graphile_postgis, public;`
- reset the database before running the tests (or, if it's fast enough, you could do it for each test - but make sure postgis is installed in `public` first!)
- prefer lots of test files over one do-it-all test file
- allow overriding the test database URL with an envvar (e.g. so you can test against different versions of PostgreSQL on Docker, or for CI). I'd use `TEST_DATABASE_URL` for this so long as we use a unique schema name.
