### ISSUE TITLE
Does this work with geometry fields?

### ISSUE THREAD

**Issue by barbalex** [graphile/postgis#21]
I can only find references to geography fields in the readme.

My project uses geometry fields. They are recognized as string.

Does this mean that geometry fields are not supported? Or have I missed something?

**Comment by mattbretl** [comment]
Both `geometry` and `geography` are definitely supported. Can you share an example where they're being exposed as String fields?

**Comment by barbalex** [comment]
My bad: I was using
```npx postgraphile --append-plugins postgraphile-plugin-connection-filter @graphile/postgis```

Today I tried this way: 
```npx postgraphile --append-plugins postgraphile-plugin-connection-filter,@graphile/postgis```

and that works:

```json
"geomPoint": {
  "geojson": "{\"type\":\"Point\",\"coordinates\":[8.52925922517908,47.5493181630711]}",
  "srid": 4326,
  "x": 8.52925922517908,
  "y": 47.5493181630711
}
```

Maybe if you add a concrete example in the docs noobs like me will stop distracting you from building such great stuff :-|

Thanks for this great tool.

**Comment by benjie** [comment]
Really the PostGraphile CLI should have thrown an error about that unused argument. Would you like to file an issue (or PR!) against PostGraphile for that?

**Comment by barbalex** [comment]
done: https://github.com/graphile/postgraphile/issues/1092
