### ISSUE TITLE
how to insert/update GeometryPoint

### ISSUE THREAD

**Issue by barbalex** [graphile/postgis#30]
I am sure this must be pretty obvious to most but I haven't figured out how to update a GeometryPoint:

```graphql
"geomPoint": {
  "geojson": "{\"type\":\"Point\",\"coordinates\":[8.529259225,47.549318163]}",
  "srid": 4326,
  "x": 8.529259225,
  "y": 47.549318163
}
```
Do I need to set all 4 values?

**Comment by benjie** [comment]
I think you just pass `geomPoint` a GeoJSON object, so:

```graphql
mutation {
  updateFooById(
    input: {
      id: 27,
      fooPatch: {
        geomPoint: {
          type: "Point"
          coordinates: [8.5, 47.5]
        }
      }
    }
  ) { ... }
}
```

**Comment by barbalex** [comment]
What I did not realize was that the type of geometry field is `GeoJSON` in mutations while it is `GeometryPoint` in queries.

So I obviously did not look carefully enough. Even so, it might help to point that out in the readme.

Thanks a lot for helping!

**Comment by benjie** [comment]
PR to README welcome :+1:

**Comment by barbalex** [comment]
Uups. Unfortunately it only works in dev - breaks in production: https://github.com/graphile/postgis/issues/31
