### ISSUE TITLE
Error on update: Geometry SRID (0) does not match column SRID (4326)

### ISSUE THREAD

**Issue by barbalex** [graphile/postgis#31]
This query:
```graphql
mutation updateTpopByIdForCoordinates($id: UUID!, $geomPoint: GeoJSON, $changedBy: String) {
  updateTpopById(input: {id: $id, tpopPatch: {geomPoint: $geomPoint, changedBy: $changedBy}}) {
    tpop {
      id
      geomPoint {
        geojson
        x
        y
        __typename
      }
      __typename
    }
    __typename
  }
}
```
using these variables:
```js
{
  id: "76c7fe44-4f62-11e7-aebe-6b56ab796555",
  geomPoint: {
    type: "Point",
    coordinates: [8.7598132757593561: 47.365852759391956]
  },
  changedBy: "z"
}

```
works fine in dev. But throws `Geometry SRID (0) does not match column SRID (4326)` in production.

Field geom_point is defined as `geometry(Point,4326)`.

What could be off?

In dev and production the versions used are:
- "postgraphile": "4.5.5"
- "@graphile-contrib/pg-order-by-related": "1.0.0-beta.6"
- "@graphile/postgis": "0.1.0"
- "graphile-build-pg": "4.5.3" (only production)
- "postgraphile-plugin-connection-filter": "1.1.3"

postgraphile is started like this:
```
pm2 start ./node_modules/.bin/postgraphile -- -c postgres://user:secret@localhost:5432/apflora --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related,@graphile/postgis --jwt-token-identifier auth.jwt_token --default-role anon --jwt-secret secret -s apflora --cors --disable-query-log --enable-query-batching  --enhance-graphiql
```

Only difference between dev and production is the version of PostgreSQL used:
- 11 in production
- 12 in dev

**Comment by benjie** [comment]
My guess is that the issue lies here:

https://github.com/graphile/postgis/blob/14ccf5b66ac94318862aead6e302e15dfd6cfd2f/src/PostgisRegisterTypesPlugin.ts#L314-L316

According to the ST_GeomFromGeoJSON docs, it defaults to 4326 since PostGIS v3.0.0, but perhaps you're running an older version of PostGIS in production?

> Enhanced: 3.0.0 parsed geometry defaults to SRID=4326 if not specified otherwise.

(Recommend using the same versions in production and development to spot issues like this earlier.)

**Comment by benjie** [comment]
It's not clear from the docs how to `specify otherwise`, so a PR with tests would be welcome.

**Comment by barbalex** [comment]
From what I understand @graphile/postgis expects geojson to update a geometry.

And it seems that PostGIS expects an srid to be explicitly passed.

It also seems that since 2016 GeoJSON expects the srid to _always_ be 4326/WGS84 as defined here: https://tools.ietf.org/html/rfc7946#section-4.

Two questions:
- How would someone work with a different srid using @graphile/postgis?
- Would it not be bad if @graphile/postgis always expected the srid to be 4326? Because that is what such a pull request would amount to, if I understand correctly

**Comment by barbalex** [comment]
I have managed to circumvent the problem by adding a crs to the GeoJSON, which is deprecated but still seems to work:

```js
{
  type: "Point",
  coordinates: [-0.1082163, 51.5685594],
  crs: {
    type: "name",
    properties: {
      name: "urn:ogc:def:crs:EPSG::4326"
    }
  }
}
```

**Comment by barbalex** [comment]
> How would someone work with a different srid using @graphile/postgis if updates happen via GeoJSON?

Hm. Probably PostGIS is wise enough to check what srid is set on the geometry field, so that should not be a problem?

**Comment by benjie** [comment]
We don't specifically limit @graphile/postgis to 4326, but it is basically the default for everything and it gets preferential treatment. I think for now saying that this workaround is required for PostGIS < v3 seems acceptable; what do you think?

**Comment by barbalex** [comment]
Yes, I think it is quite acceptable. But good to know.

**Comment by benjie** [comment]
Definitely; thanks for sharing the solution 👍
