### ISSUE TITLE
how to install this plugin? publish latest version to npm?

### ISSUE THREAD

**Issue by derhuerst** [graphile/postgis#48]
### Feature description

I would like to use this plugin via PostGraphile's `--append-plugins` flag, but that seems to require a Node.js-native (thus non-Typescript) entrypoint within the plugin.

As the latest npm version is 3 years old, and changes have been made since then, I wonder if a new release should be published to npm. An alternative would be to check the TypeScript build artefacts (`dist`) into a Git tag.

### Motivating example

The readme mentions just using the plugin like this: `--apend-plugins @graphile/postgis`.

### Breaking changes

–

### Supporting development

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

---

```shell
node -v
# v18.8.0
postgraphile --version
# 4.12.11
```

**Comment by benjie** [comment]
I've published the latest as `@graphile/postgis@0.2.0-0` but I don't have a PostGIS DB handy to test with. If `postgraphile --append-plugins @graphile/postgis` doesn't work, try `postgraphile --append-plugins @graphile/postgis:default`?

**Comment by derhuerst** [comment]
It works, thank you! Indeed, the `.default`/`:default` is necessary.

**Comment by benjie** [comment]
@derhuerst Are you running an ancient PostGraphile version?

**Comment by derhuerst** [comment]
Sorry, that was fake news. It works with both `@graphile/postgis:default` and with `@graphile/postgis`, using PostGraphile `4.12.11`.

**Comment by derhuerst** [comment]
I'm currently checking if this is an error on my side, but it seems that `@graphile/postgis@0.2.0-0` is... empty?

**Comment by benjie** [comment]
Nope: https://unpkg.com/browse/@graphile/postgis@0.2.0-0/
